name: "Check diff change of PR"
description: "PR should not too many files, if not it need to be explained why"
inputs:
  max-file:
    description: "max number of files change"
    required: true
    default: "10"
  token:
    description: "GITHUB_TOKEN or a repo scoped PAT."
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
